### PR TITLE
Added support for resources (attachments) when creating a note.

### PR DESCRIPTION
**Pull request by ddierickx**
Implemented support for adding attachments to a new note using '--resource FILENAME'. The attached files (png/pdf/...) are embedded in the content.

Support for resources in update has not been implemented but should not be too hard to do.

### CODE REVIEW

**Comment by silviuvulcan** [comment]
Any chance we will se this implemented? It's really useful for scanner automation

**Comment by VitaliyRodnenko** [comment]
Thx for feedback, I'll solve conflicts and merge that with master. Can't do that immediately because of lack of free time. But I promise not to forget about it. Hope to realize that on weekend.

**Comment by silviuvulcan** [comment]
That would be awesome!

**Comment by VitaliyRodnenko** [comment]
Hope that works well, need more time to test it well. But it has been merged with master.

**Comment by silviuvulcan** [comment]
Hm,

I just updated and I see this when trying to create a note:

```
geeknote create --title Test1 --content something --resource ftest.pdf
    : Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 893, in main
    Notes().create(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 637, in create
    inputData = self._parseInput(title, content, tags, notebook, resource)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 705, in _parseInput
    "resources": resources if resources else [],
NameError: global name 'resources' is not defined
```  

Thanks

**Comment by padi** [comment]
@silviuvulcan getting the same error (NameError: global name 'resources' is not defined) after installing this for the first time today. Can't create any new note

**Comment by padi** [comment]
@silviuvulcan looks like the recent commits messed up the `master` branch. Just checkout at an earlier commit, install and try creating a note again. Not sure which SHA is the latest stable working version, but here's what worked for me: 4423092

**Comment by silviuvulcan** [comment]
Indeed older 4423092 works. My error report was in reply to the resources merge:
"Hope that works well, need more time to test it well. But it has been merged with master."

Cheers,
Silviu

**Pull request closed without merging**
