### PR TITLE
fix parsing hpts and hptsh for login form

### LINKED ISSUE #288: Incorrect login or password
I am unable to login to my Evernote account. I use the login command and when prompted for my login information I have tried providing my email and username login with the correct password and both return "Sorry, incorrect login or password" I checked my login by relogging on the Evernote site and I have changed my password to make sure the login information is correct, but I still get the same error.

### PR DESCRIPTION
**Pull request by chrox**
This should fix #288.

Please refer to this commit in [evernote-sdk-lua](https://github.com/koreader/evernote-sdk-lua/commit/cfe65376a5ee04ca8f1f10993f5ff9cceaad2857) used in [KoReader](https://github.com/koreader/koreader).

### CODE REVIEW

**Comment by cerkut** [comment]
@VitaliyRodnenko please merge this simple parsing fix, without this geeknote won't work on unix terminals. Also, making a release to be included in homebrew is not a bad idea: https://github.com/Homebrew/homebrew/pull/14202

**Comment by kyleskrinak** [comment]
I was unable to login without applying this patch on Mac 10.10.3 and ubuntu 14.04

**Comment by tomfbush** [comment]
Fixed for me on OSX 10.10.3 too

**Comment by khadiwala** [comment]
+1. couldn't login without this on two different boxes.

**Comment by VitaliyRodnenko** [comment]
Thank you for patch!

**Pull request merged**
